# Hexo Configuration / Hexo è¨­å®šæª”
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site / ç¶²ç«™è³‡è¨Š
title: "â­ï¸ Sam çš„æ–‡ç« åˆ†äº«(æŒçºŒç´¯ç©ä¸­ğŸƒâ€â™‚ï¸)(Hexo 1.0.2 ç‰ˆ)"
subtitle: ""
description: ""
keywords: ""
author: "Sam"
language: "en"
timezone: "Asia/Taipei"

# URL / ç¶²å€è¨­å®š
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
## åœ¨é€™è£¡è¨­å®šä½ çš„ç¶²ç«™ç¶²å€ï¼Œä¾‹å¦‚ GitHub Page è«‹è¨­ç‚º 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks / è¨­ç‚º false å¯ç§»é™¤ç¶²å€çµå°¾çš„ 'index.html'
  trailing_html: true # Set to false to remove trailing '.html' from permalinks / è¨­ç‚º false å¯ç§»é™¤ç¶²å€çµå°¾çš„ '.html'

# Directory / ç›®éŒ„è¨­å®š
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing / æ–‡ç« å¯«ä½œ
new_post_name: :title.md # File name of new posts / æ–°æ–‡ç« çš„æª”åæ ¼å¼
default_layout: post
titlecase: false # Transform title into titlecase / æ¨™é¡Œæ˜¯å¦è½‰ç‚ºæ¨™é¡Œæ ¼å¼
external_link:
  enable: true # Open external links in new tab / å¤–éƒ¨é€£çµæ–°åˆ†é é–‹å•Ÿ
  field: site # Apply to the whole site / å¥—ç”¨æ–¼æ•´å€‹ç¶²ç«™
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true # é¡¯ç¤ºè¡Œè™Ÿ / Show line number
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true # é¡¯ç¤ºè¡Œè™Ÿ / Show line number
  tab_replace: ""

# Home page setting / é¦–é è¨­å®š
# path: Root path for your blogs index page. (default = '') / ç¶²èªŒé¦–é è·¯å¾‘ (é è¨­ç‚ºç©º)
# per_page: Posts displayed per page. (0 = disable pagination) / æ¯é é¡¯ç¤ºæ–‡ç« æ•¸ (0 è¡¨ç¤ºä¸åˆ†é )
# order_by: Posts order. (Order by date descending by default) / æ–‡ç« æ’åº (é è¨­ç‚ºæ—¥æœŸæ–°åˆ°èˆŠ)
index_generator:
  path: ""
  per_page: 5 # æ¯é é¡¯ç¤ºæ–‡ç« æ•¸ (0 è¡¨ç¤ºä¸åˆ†é )
  order_by: -date

# Category & Tag / åˆ†é¡èˆ‡æ¨™ç±¤
default_category: uncategorized
category_map:
tag_map:

# Metadata elements / ç¶²é ä¸­ç¹¼è³‡æ–™
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format / æ—¥æœŸèˆ‡æ™‚é–“æ ¼å¼
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD # æ—¥æœŸæ ¼å¼
time_format: HH:mm:ss   # æ™‚é–“æ ¼å¼
## updated_option supports 'mtime', 'date', 'empty'
## updated_option æ”¯æ´ 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination / åˆ†é è¨­å®š
## Set per_page to 0 to disable pagination / è¨­ç‚º 0 å¯é—œé–‰åˆ†é 
per_page: 10
pagination_dir: page

# Include / Exclude file(s) / åŒ…å«æˆ–æ’é™¤æª”æ¡ˆ
## include:/exclude: options only apply to the 'source/' folder
## åªé©ç”¨æ–¼ 'source/' è³‡æ–™å¤¾
include: []
exclude: []
ignore:

# Extensions / æ“´å……åŠŸèƒ½
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment / éƒ¨ç½²è¨­å®š
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ""
